### ISSUE TITLE
Super Issue: Update submission portal for new study page design 

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/submission-schema#161]
The study page refresh squad has identified new slots and made updates that requires additional information be collected in the NMDC submission portal.

- [x] research vs consortia study type
- [x] microbiomedata/submission-schema#224
- [ ] #314
- [x] microbiomedata/nmdc-server#1529
- [x] https://github.com/microbiomedata/issues/issues/229
- [ ] microbiomedata/submission-schema#217
- [ ] #315
- [x] microbiomedata/submission-schema#252
- [ ] Add better instruction for finding project IDs.

**Comment by mslarae13** [comment]
"a place to share links"

<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/ac9920e3-cfa2-4a97-83c1-7c578ec45563" />

Different from this?

I can't remember!
@lamccue , do you recall if this was something different? 
https://microbiomedata.github.io/nmdc-schema/websites/

**Comment by mslarae13** [comment]
"research vs consortia study type"
This will just confuse researchers, we get mostly research studies, and the dagit job has a place to identify this on ingest. We'll just not add this to the submission portal.

**Comment by lamccue** [comment]
> "a place to share links"
> 
> <img alt="Image" width="1167" src="https://private-user-images.githubusercontent.com/44581429/425232758-ac9920e3-cfa2-4a97-83c1-7c578ec45563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI1MTkyMjksIm5iZiI6MTc0MjUxODkyOSwicGF0aCI6Ii80NDU4MTQyOS80MjUyMzI3NTgtYWM5OTIwZTMtY2ZhMi00YTk3LTgzYzEtN2M1NzhlYzQ1NTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzIxVDAxMDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNTdmNmQwMTE1ZTI2NGFjZjMwMDQ5YzFkNWYyOGU5ZTA2NmZjMmYyY2FkYjYxODVlMmViYWZhZWNhNjNjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1StP5T_l3zVU9iENlLBNlE17bK34rk20e07b9OL_SAA">
> Different from this?
> 
> I can't remember! [@lamccue](https://github.com/lamccue) , do you recall if this was something different? https://microbiomedata.github.io/nmdc-schema/websites/

Yes, I think that was what we meant - that field in the submission portal, which gives the user a way to provide a url to a website that will appear on their study page under "Links".

**Comment by mslarae13** [comment]
Ok! So that sounds like what we have so I'll consider links resolved.

**Comment by mslarae13** [comment]
@pkalita-lbl working on images.

**Comment by mslarae13** [comment]
@JamesTessmer about to start DOI capture
